title: Kendall Ash
description: Graduate Ecology Student
url: "https://ashkenda.github.io"
baseurl: ""

author:
  name: Kendall Ash
  email: ashkenda@msu.edu
  github: ashkenda
  linkedin: yourlinkedin
  twitter: yourtwitter   # optional, remove if not needed

# Build settings
markdown: kramdown
theme: DARK-POOLE
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
